# define services
services:
  # alignment tool service
  batchalign:
    # host networking
    network_mode: bridge
    # pull the latest docker image
    image: jemokajack/batchalign:latest
    # build:
    #   context: batchalign
    # exposed secrets
    environment:
      - REV_API=__REV_API__
      - BA_MODE=+__MODE__+
    # volumes
    volumes:
      - __IN_PATH__:/root/in
      - __OUT_PATH__:/root/out
      - __MODEL_PATH__:/root/model
    # expose tty
    stdin_open: true # docker run -i
    tty: true        # docker run -t
