{% set name = "batchalign" %}
{% set version = "0.0.15" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/TalkBank/batchalign.git
  git_rev: master

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - pip
  run:
    - python
    - requests
    - six
    - websocket-client
    - numpy 1.22.*
    - sqlalchemy 1.4.46
    - praatio 5.1.1
    - montreal-forced-aligner 2.0.6
    - pytorch
    - transformers 4.24.*
    - tokenizers
    - nltk
    - libcxx

build:
  entry_points:
    - batchalign = baln.command_line:mainloop

about:
  home: https://github.com/TalkBank/batchalign
  summary: 'an utility to generate and align CHAT files with ASR + Forced Alignment'
  dev_url: https://github.com/TalkBank/batchalign.git
  doc_url: https://github.com/TalkBank/batchalign

