{% set name = "batchalign" %}
{% set version = "0.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/TalkBank/batchalign.git
  git_rev: feat/conda

requirements:
  host:
    - python
    - pip
    - make
    - {{ compiler('c') }}
  run:
    - python
    - numpy 1.22.*
    - montreal-forced-aligner
    - pytorch
    - transformers
    - tokenizers
    - nltk

about:
  home: https://github.com/TalkBank/batchalign
  summary: 'an utility to generate and align CHAT files with ASR + Forced Alignment'
  dev_url: https://github.com/TalkBank/batchalign.git
  doc_url: https://github.com/TalkBank/batchalign

