{% set name = "batchalign" %}
{% set version = "0.1.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/TalkBank/batchalign.git
  git_rev: feat/next

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - pip
  run:
    - python 3.10.*
    - requests
    - six
    - websocket-client
    - numpy 1.22.*
    - sqlalchemy 2.0.3
    - praatio 6.0.0
    - pgvector 0.4.0
    - pgvector-python 0.1.6
    - montreal-forced-aligner 2.1.5
    - pytorch
    - transformers 4.24.*
    - tokenizers
    - nltk
    - libcxx
    - stanza

build:
  entry_points:
    - batchalign = baln.cli:batchalign

about:
  home: https://github.com/TalkBank/batchalign
  summary: 'CHAT file batch-processing utilities'
  dev_url: https://github.com/TalkBank/batchalign.git
  doc_url: https://github.com/TalkBank/batchalign

