{% set name = "batchalign" %}
{% set version = "0.3.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/TalkBank/batchalign.git
  git_rev: master

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python 3.10.12
    - pip
  run:
    - python 3.10.12
    - requests
    - six
    - websocket-client
    - numpy 1.22.*
    - sqlalchemy 2.0.3
    - praatio 6.0.0
    - pgvector 0.4.0
    - scikit-learn 1.2.2
    - hdbscan 0.8.29
    - pgvector-python 0.1.6
    - montreal-forced-aligner 2.1.7
    - pytorch
    - transformers 4.24.*
    - scikit-learn 1.2.2
    - hdbscan 0.8.29
    - tokenizers
    - h5py
    - loguru 0.7.0
    - nltk
    - libcxx
    - stanza
    - flask 2.3.*
    - gunicorn 20.1.*
    - flask-cors 4.0.0
    - mysql-connector-python 8.0.31

build:
  entry_points:
    - batchalign = baln.cli:batchalign

about:
  home: https://github.com/TalkBank/batchalign
  summary: 'CHAT file batch-processing utilities'
  dev_url: https://github.com/TalkBank/batchalign.git
  doc_url: https://github.com/TalkBank/batchalign

