name: Build and Release for Anaconda

on:
  push:
    branches:
      - master

jobs:
  conda_build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          miniforge-version: latest
      - name: Install Conda build tools
        run: conda install -y conda-build conda-verify
      - name: Update Conda
        run: conda update -y conda
      - name: Install mamba
        run: conda install -y mamba
      - name: Build batchalign
        run: conda mambabuild .
        


