name: Build and Release for Anaconda

on:
  push:
    branches:
      - master

jobs:
  conda_build:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Remove actions folder (POSIX) # this is required for Conda to not freak out at the yml file inside
        if: ${{ matrix.os != 'windows-latest' }} 
        run: rm -rf .github
      - name: Remove actions folder (Win) # this is required for Conda to not freak out at the yml file inside
        if: ${{ matrix.os == 'windows-latest' }} 
        run: Remove-Item ".github\*" -Force -Recurse
      - name: Install mingw gcc (windows)
        if: ${{ matrix.os == 'windows-latest' }} 
        run: conda install -y m2w64-toolchain
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          miniforge-version: latest
      - name: Install Conda build tools
        run: conda install -y conda-build conda-verify
      - name: Update Conda
        run: conda update -y conda
      - name: Install mamba and boa (dependency resolver)
        run: conda install -y mamba boa
      - name: Build batchalign
        run: conda mambabuild . -c pytorch -c conda-forge --no-test
        


