name: Build and Release for Anaconda

on:
  push:
    branches:
      - "**"

jobs:
  conda_build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Remove actions folder (POSIX) # this is required for Conda to not freak out at the yml file inside
        if: ${{ matrix.os != 'windows-latest' }} 
        run: rm -rf .github
      - name: Remove actions folder (Win) # this is required for Conda to not freak out at the yml file inside
        if: ${{ matrix.os == 'windows-latest' }} 
        run: Remove-Item ".github\*" -Force -Recurse
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          miniforge-version: latest
      - name: Install Conda build tools
        run: conda install -y conda-build conda-verify
      - name: Update Conda
        run: conda update -y conda
      - name: Brotli dependency
        if: ${{ matrix.os == 'windows-latest' }} 
        run: conda install -c anaconda urllib3
      - name: Install mamba and boa (dependency resolver)
        run: conda install -y mamba boa
      - name: Install mingw (Win)
        if: ${{ matrix.os == 'windows-latest' }} 
        run: conda install -y m2w64-toolchain m2w64-gcc
      - name: Build batchalign
        run: conda mambabuild . -c pytorch -c conda-forge --no-test
      - name: Upload Build Artifact (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }} 
        uses: actions/upload-artifact@v3
        with:
          name: Linux batchalign
          path: /usr/share/miniconda3/conda-bld/linux-64/*.tar.bz2
      - name: Upload Build Artifact (macOS)
        if: ${{ matrix.os == 'macos-latest' }} 
        uses: actions/upload-artifact@v3
        with:
          name: macOS batchalign
          path: /Users/runner/miniconda3/conda-bld/osx-64/*.tar.bz2
      - name: Upload Build Artifact (Windows)
        if: ${{ matrix.os == 'windows-latest' }} 
        uses: actions/upload-artifact@v3
        with:
          name: Windows batchalign
          path: C:\Miniconda3\conda-bld\win-64\*.tar.bz2
